apiVersion: v2
name: opsi
description: OPSI config server with persistent data, native TLS and optional PXE on Kubernetes.
type: application
version: 0.2.0
appVersion: "4.3.56.11"
kubeVersion: ">=1.25.0-0"
home: https://opsi.org
sources:
  - https://github.com/CodeOpsMS/opsi-helm-chart
  - https://github.com/opsi-org/opsi-docker
keywords: [opsi, endpoint-management, pxe, tftp]
maintainers:
  - name: CodeOpsMS
    url: https://github.com/CodeOpsMS
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: integration-delivery
